import{a as p,S as f,i as s}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m="51467022-cc438a4dec995b2b9f6e09d1a",y="https://pixabay.com/api/";async function h(o){try{return(await p.get(y,{params:{key:m,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(r){console.error(r)}}const c=document.querySelector(".gallery"),g=new f(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const r=o.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:i,comments:d,downloads:u})=>`<li class="photo-card">
      <a href="${a}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${d}</p>
        <p><b>Downloads:</b> ${u}</p>
      </div>
    </li>`).join("");c.insertAdjacentHTML("beforeend",r),g.refresh()}function L(){c.innerHTML=""}const l=document.querySelector(".loader");function S(){l.classList.remove("loader--hidden")}function q(){l.classList.add("loader--hidden")}const w=document.querySelector(".form"),v=document.querySelector('[name="search-text"]');document.querySelector("button");document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector("#loader");o&&o.classList.add("is-hidden")});w.addEventListener("submit",E);async function E(o){o.preventDefault();const r=v.value.trim();if(!r){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}try{L(),S();const n=await h(r);if(q(),n.hits.length===0){s.warning({title:"Warning",message:"Sorry, no images found for your query.",position:"topRight"});return}b(n.hits)}catch(n){console.error(n),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
