import{a as p,S as f,i as s}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m="51467022-cc438a4dec995b2b9f6e09d1a",y="https://pixabay.com/api/";async function g(n){try{return(await p.get(y,{params:{key:m,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(r){console.error(r)}}const c=document.querySelector(".gallery"),h=new f(".gallery a",{captionsData:"alt",captionDelay:250});function b(n){const r=n.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:i,comments:u,downloads:d})=>`<li class="photo-card">
      <a href="${a}">
        <img src="${o}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${u}</p>
        <p><b>Downloads:</b> ${d}</p>
      </div>
    </li>`).join("");c.insertAdjacentHTML("beforeend",r),h.refresh()}function L(){c.innerHTML=""}const l=document.querySelector(".loader");function S(){l.classList.remove("loader--hidden")}function w(){l.classList.add("loader--hidden")}const q=document.querySelector(".form"),v=document.querySelector('[name="search-text"]');document.querySelector("button");q.addEventListener("submit",P);async function P(n){n.preventDefault();const r=v.value.trim();if(!r){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}try{L(),S();const o=await g(r);if(w(),o.hits.length===0){s.warning({title:"Warning",message:"Sorry, no images found for your query.",position:"topRight"});return}b(o.hits)}catch(o){console.error(o),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
